export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
